# Generated by Django 5.1 on 2024-09-29 05:41

import accounts.utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_assets_liabilities_alter_assets_other_assets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='liabilities',
            field=accounts.utils.fields.EncryptedField(),
        ),
        migrations.AlterField(
            model_name='assets',
            name='other_assets',
            field=accounts.utils.fields.EncryptedField(),
        ),
        migrations.AlterField(
            model_name='assets',
            name='real_estates',
            field=accounts.utils.fields.EncryptedField(),
        ),
        migrations.AlterField(
            model_name='assets',
            name='vehicles',
            field=accounts.utils.fields.EncryptedField(),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='annual_expenses',
            field=accounts.utils.fields.EncryptedField(),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='debt',
            field=accounts.utils.fields.EncryptedField(),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='monthly_expenses',
            field=accounts.utils.fields.EncryptedField(),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='one_time_expenses',
            field=accounts.utils.fields.EncryptedField(),
        ),
        migrations.AlterField(
            model_name='income',
            name='employer_contributions',
            field=accounts.utils.fields.EncryptedField(),
        ),
        migrations.AlterField(
            model_name='income',
            name='expected_salary_growth',
            field=accounts.utils.fields.EncryptedField(),
        ),
        migrations.AlterField(
            model_name='income',
            name='monthly_income',
            field=accounts.utils.fields.EncryptedField(),
        ),
        migrations.AlterField(
            model_name='income',
            name='other_sources',
            field=accounts.utils.fields.EncryptedField(),
        ),
        migrations.AlterField(
            model_name='personal',
            name='age',
            field=accounts.utils.fields.EncryptedField(),
        ),
        migrations.AlterField(
            model_name='personal',
            name='dependents',
            field=accounts.utils.fields.EncryptedField(),
        ),
        migrations.AlterField(
            model_name='personal',
            name='retirement_age',
            field=accounts.utils.fields.EncryptedField(),
        ),
        migrations.AlterField(
            model_name='savings',
            name='current_savings',
            field=accounts.utils.fields.EncryptedField(),
        ),
        migrations.AlterField(
            model_name='savings',
            name='investments',
            field=accounts.utils.fields.EncryptedField(),
        ),
        migrations.AlterField(
            model_name='savings',
            name='retirement_savings',
            field=accounts.utils.fields.EncryptedField(),
        ),
    ]
